### PR TITLE
fixes qosBasic and rejectBasic

### LINKED ISSUE #16: rejectBasic and qosBasic don't work
rejectBasic() doesn't work because it is in the wrong state array in AmqpClient.js.  It is in the array for synchronous methods but it is asynchronous so it throws an error.  
qosBasic doesn't work because it is not in any of the state arrays in AmqpClient.js.
I am working on a patch to fix these issues.

### PR DESCRIPTION
**Pull request by bradjorgensen**
Adds the needed qosBasic things to the appropriate state arrays so it will work.
Moves rejectBasic to the correct channel state array.
fixes #16

### CODE REVIEW

**Comment by sanjay-saxena** [comment]
Thanks for looking into these issues! If you have sample code snippet that was used to test these changes, we can add them to the integration test suite.

**Comment by robinzimmermann** [comment]
Hi Brad. In the meantime, please look in [CONTRIBUTING.md](https://github.com/kaazing/kaazing-amqp-0-9-1-client-javascript/blob/develop/CONTRIBUTING.md) for instructions on electronically signing the Contributor License Agreement (CLA). This is necessary before any pull request can be merged.

**Comment by sanjay-saxena** [comment]
Hi Brad -- Can you please include the sample code snippet that you had used to test your changes? We can add it to our test suite. In order for this pull request to make into AMQP 4.0.7, we need to add a test.

**Comment by sbadugu** [comment]
There is a issue filed for this and it will be addressed [here](https://github.com/kaazing/javascript.client/issues/5)

**Pull request closed without merging**
